name: MSBuild

on: [push]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:Platform="x86"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Demo
        path: .\demo\Engine.Demo.Shell\bin\Release\

